<a href="https://colab.research.google.com/github/Ali-Alinejad/Ai/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.17.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [14]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [15]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [16]:
y

array([1, 0, 1, ..., 1, 1, 0])

### Encoding categorical data

Label Encoding the "Gender" column

* change gender col to 0 or 1 with sklearn

In [18]:
import sklearn.preprocessing
le = sklearn.preprocessing.LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the "Geography" column
* change location to this
- change france to 1 . 0 . 0
- change Spain to  0 . 0 . 1
-change Germany to 0 . 1 . 0

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [23]:
import sklearn.model_selection
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size = 0.2, random_state = 0)
x_train.shape, x_test.shape

((8000, 12), (2000, 12))

### Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train , x_test

(array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         -1.03227043,  1.10643166],
        [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
          0.9687384 , -0.74866447],
        [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
         -1.03227043,  1.48533467],
        ...,
        [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
         -1.03227043,  1.41231994],
        [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
          0.9687384 ,  0.84432121],
        [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         -1.03227043,  0.32472465]]),
 array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
          0.9687384 ,  1.61085707],
        [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
         -1.03227043,  0.49587037],
        [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
          0.9687384 , -0.42478674],
        ...,
        [-1.01460667, -0.5698444 ,  1.74309049, ...,  

## Part 2 - Building the ANN

### Initializing the ANN

In [25]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

در نهایت:

    این خط کد یک لایه با 6 نورون و تابع فعال‌سازی ReLU به مدل اضافه می‌کند.
    این لایه برای یادگیری ویژگی‌های داده در فرآیند آموزش شبکه عصبی استفاده می‌شود.
    اگر این اولین لایه باشد، ابعاد ورودی به‌طور خودکار از داده‌های آموزشی تشخیص داده می‌شود.

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

### Training the ANN on the Training set

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

### Making the Confusion Matrix