In [10]:
from sklearn.datasets import load_breast_cancer
import matplotlib,poplib as mlp
import numpy as np 
import pandas as pd

bc = load_breast_cancer();

print(bc.DESCR)


.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [13]:
bc.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [20]:
bc.data.shape

(569, 30)

# Pre Processing

In [36]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(bc.data,bc.target , test_size=0.2)

In [38]:
print(f"Feature => train :{x_train.shape} - test:{x_test.shape} ")
print(f"Label => train :{y_train.shape} - test:{y_test.shape} ")



Feature => train :(455, 30) - test:(114, 30) 
Label => train :(455,) - test:(114,) 


In [39]:
x_train[0]

array([1.831e+01, 2.058e+01, 1.208e+02, 1.052e+03, 1.068e-01, 1.248e-01,
       1.569e-01, 9.451e-02, 1.860e-01, 5.941e-02, 5.449e-01, 9.225e-01,
       3.218e+00, 6.736e+01, 6.176e-03, 1.877e-02, 2.913e-02, 1.046e-02,
       1.559e-02, 2.725e-03, 2.186e+01, 2.620e+01, 1.422e+02, 1.493e+03,
       1.492e-01, 2.536e-01, 3.759e-01, 1.510e-01, 3.074e-01, 7.863e-02])

# Normalize

In [41]:
from sklearn.preprocessing import  MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [43]:
x_train[0]

array([0.5361825 , 0.3676023 , 0.53216778, 0.38569306, 0.58835669,
       0.39435882, 0.36761949, 0.46973161, 0.4040404 , 0.19903117,
       0.15694369, 0.12427069, 0.1159591 , 0.11672751, 0.15171499,
       0.12405744, 0.07356061, 0.19814359, 0.14386502, 0.06322983,
       0.55277778, 0.37793177, 0.51310861, 0.4027966 , 0.51528759,
       0.21956709, 0.30023962, 0.52668294, 0.29745713, 0.15472911])